# party / mongo-pg
# MongoDB mongo.party -> PostgreSQL master.party
mms.recon.domains.party.profiles.mongo-pg.datasources.source=mongo
mms.recon.domains.party.profiles.mongo-pg.datasources.target=landing
mms.recon.domains.party.profiles.mongo-pg.migrationKey.type=SINGLE
mms.recon.domains.party.profiles.mongo-pg.migrationKey.columns[0]=party_id
mms.recon.domains.party.profiles.mongo-pg.recon.mode=MISMATCH_DETAILS
mms.recon.domains.party.profiles.mongo-pg.source.collection=party
mms.recon.domains.party.profiles.mongo-pg.source.fields[0]=party_name
mms.recon.domains.party.profiles.mongo-pg.source.fields[1]=country_code
mms.recon.domains.party.profiles.mongo-pg.source.fields[2]=status
mms.recon.domains.party.profiles.mongo-pg.source.query={}
mms.recon.domains.party.profiles.mongo-pg.target.schema=master
mms.recon.domains.party.profiles.mongo-pg.target.table=party
mms.recon.domains.party.profiles.mongo-pg.target.fields[0]=party_name
mms.recon.domains.party.profiles.mongo-pg.target.fields[1]=country_code
mms.recon.domains.party.profiles.mongo-pg.target.fields[2]=status
