# party / pg-bigquery
# PostgreSQL landing.party -> BigQuery bq.party (Calcite)
mms.recon.domains.party.profiles.pg-bigquery.datasources.source=landing
mms.recon.domains.party.profiles.pg-bigquery.datasources.target=bq
mms.recon.domains.party.profiles.pg-bigquery.migrationKey.type=SINGLE
mms.recon.domains.party.profiles.pg-bigquery.migrationKey.columns[0]=party_id
mms.recon.domains.party.profiles.pg-bigquery.recon.mode=MISMATCH_DETAILS
mms.recon.domains.party.profiles.pg-bigquery.source.schema=landing
mms.recon.domains.party.profiles.pg-bigquery.source.table=party
mms.recon.domains.party.profiles.pg-bigquery.source.fields[0]=party_name
mms.recon.domains.party.profiles.pg-bigquery.source.fields[1]=country_code
mms.recon.domains.party.profiles.pg-bigquery.source.fields[2]=status
mms.recon.domains.party.profiles.pg-bigquery.target.table=party
mms.recon.domains.party.profiles.pg-bigquery.target.fields[0]=party_name
mms.recon.domains.party.profiles.pg-bigquery.target.fields[1]=country_code
mms.recon.domains.party.profiles.pg-bigquery.target.fields[2]=status
