# party / pg-pg-same-schema
# PostgreSQL public.party_landing -> PostgreSQL public.party_master (same schema, different tables)
mms.recon.domains.party.profiles.pg-pg-same-schema.datasources.source=landing
mms.recon.domains.party.profiles.pg-pg-same-schema.datasources.target=landing
mms.recon.domains.party.profiles.pg-pg-same-schema.migrationKey.type=SINGLE
mms.recon.domains.party.profiles.pg-pg-same-schema.migrationKey.columns[0]=party_id
mms.recon.domains.party.profiles.pg-pg-same-schema.recon.mode=MISMATCH_DETAILS
mms.recon.domains.party.profiles.pg-pg-same-schema.source.schema=public
mms.recon.domains.party.profiles.pg-pg-same-schema.source.table=party_landing
mms.recon.domains.party.profiles.pg-pg-same-schema.source.fields[0]=party_name
mms.recon.domains.party.profiles.pg-pg-same-schema.source.fields[1]=country_code
mms.recon.domains.party.profiles.pg-pg-same-schema.source.fields[2]=status
mms.recon.domains.party.profiles.pg-pg-same-schema.target.schema=public
mms.recon.domains.party.profiles.pg-pg-same-schema.target.table=party_master
mms.recon.domains.party.profiles.pg-pg-same-schema.target.fields[0]=party_name
mms.recon.domains.party.profiles.pg-pg-same-schema.target.fields[1]=country_code
mms.recon.domains.party.profiles.pg-pg-same-schema.target.fields[2]=status
