# party / mongo-bigquery
# MongoDB mongo.party -> BigQuery bq.party (Calcite)
mms.recon.domains.party.profiles.mongo-bigquery.datasources.source=mongo
mms.recon.domains.party.profiles.mongo-bigquery.datasources.target=bq
mms.recon.domains.party.profiles.mongo-bigquery.migrationKey.type=SINGLE
mms.recon.domains.party.profiles.mongo-bigquery.migrationKey.columns[0]=party_id
mms.recon.domains.party.profiles.mongo-bigquery.recon.mode=MISMATCH_DETAILS
mms.recon.domains.party.profiles.mongo-bigquery.source.collection=party
mms.recon.domains.party.profiles.mongo-bigquery.source.fields[0]=party_name
mms.recon.domains.party.profiles.mongo-bigquery.source.fields[1]=country_code
mms.recon.domains.party.profiles.mongo-bigquery.source.fields[2]=status
mms.recon.domains.party.profiles.mongo-bigquery.source.query={}
mms.recon.domains.party.profiles.mongo-bigquery.target.table=party
mms.recon.domains.party.profiles.mongo-bigquery.target.fields[0]=party_name
mms.recon.domains.party.profiles.mongo-bigquery.target.fields[1]=country_code
mms.recon.domains.party.profiles.mongo-bigquery.target.fields[2]=status
