# party / bigquery-bigquery
# BigQuery party_landing -> BigQuery party
mms.recon.domains.party.profiles.bigquery-bigquery.datasources.source=bq
mms.recon.domains.party.profiles.bigquery-bigquery.datasources.target=bq
mms.recon.domains.party.profiles.bigquery-bigquery.migrationKey.type=SINGLE
mms.recon.domains.party.profiles.bigquery-bigquery.migrationKey.columns[0]=party_id
mms.recon.domains.party.profiles.bigquery-bigquery.recon.mode=MISMATCH_DETAILS
mms.recon.domains.party.profiles.bigquery-bigquery.source.table=party_landing
mms.recon.domains.party.profiles.bigquery-bigquery.source.fields[0]=party_name
mms.recon.domains.party.profiles.bigquery-bigquery.source.fields[1]=country_code
mms.recon.domains.party.profiles.bigquery-bigquery.source.fields[2]=status
mms.recon.domains.party.profiles.bigquery-bigquery.target.table=party
mms.recon.domains.party.profiles.bigquery-bigquery.target.fields[0]=party_name
mms.recon.domains.party.profiles.bigquery-bigquery.target.fields[1]=country_code
mms.recon.domains.party.profiles.bigquery-bigquery.target.fields[2]=status
