# account / pg-pg
# PostgreSQL landing.account -> PostgreSQL master.account (counts only)
mms.recon.domains.account.profiles.pg-pg.datasources.source=landing
mms.recon.domains.account.profiles.pg-pg.datasources.target=landing
mms.recon.domains.account.profiles.pg-pg.migrationKey.type=SINGLE
mms.recon.domains.account.profiles.pg-pg.migrationKey.columns[0]=account_id
mms.recon.domains.account.profiles.pg-pg.recon.mode=COUNTS
mms.recon.domains.account.profiles.pg-pg.source.schema=landing
mms.recon.domains.account.profiles.pg-pg.source.table=account
mms.recon.domains.account.profiles.pg-pg.source.fields[0]=account_name
mms.recon.domains.account.profiles.pg-pg.source.fields[1]=status
mms.recon.domains.account.profiles.pg-pg.target.schema=master
mms.recon.domains.account.profiles.pg-pg.target.table=account
mms.recon.domains.account.profiles.pg-pg.target.fields[0]=account_name
mms.recon.domains.account.profiles.pg-pg.target.fields[1]=status
