# party / pg-mongo
# PostgreSQL landing.party -> MongoDB mongo.party
mms.recon.domains.party.profiles.pg-mongo.datasources.source=landing
mms.recon.domains.party.profiles.pg-mongo.datasources.target=mongo
mms.recon.domains.party.profiles.pg-mongo.migrationKey.type=SINGLE
mms.recon.domains.party.profiles.pg-mongo.migrationKey.columns[0]=party_id
mms.recon.domains.party.profiles.pg-mongo.recon.mode=MISMATCH_DETAILS
mms.recon.domains.party.profiles.pg-mongo.source.schema=landing
mms.recon.domains.party.profiles.pg-mongo.source.table=party
mms.recon.domains.party.profiles.pg-mongo.source.fields[0]=party_name
mms.recon.domains.party.profiles.pg-mongo.source.fields[1]=country_code
mms.recon.domains.party.profiles.pg-mongo.source.fields[2]=status
mms.recon.domains.party.profiles.pg-mongo.target.collection=party
mms.recon.domains.party.profiles.pg-mongo.target.fields[0]=party_name
mms.recon.domains.party.profiles.pg-mongo.target.fields[1]=country_code
mms.recon.domains.party.profiles.pg-mongo.target.fields[2]=status
mms.recon.domains.party.profiles.pg-mongo.target.query={}
