# party / csv-pg
# CSV files via Calcite -> PostgreSQL master.party
mms.recon.domains.party.profiles.csv-pg.datasources.source=csv
mms.recon.domains.party.profiles.csv-pg.datasources.target=landing
mms.recon.domains.party.profiles.csv-pg.migrationKey.type=SINGLE
mms.recon.domains.party.profiles.csv-pg.migrationKey.columns[0]=party_id
mms.recon.domains.party.profiles.csv-pg.recon.mode=MISMATCH_DETAILS
mms.recon.domains.party.profiles.csv-pg.source.table=party
mms.recon.domains.party.profiles.csv-pg.source.fields[0]=party_name
mms.recon.domains.party.profiles.csv-pg.source.fields[1]=country_code
mms.recon.domains.party.profiles.csv-pg.source.fields[2]=status
mms.recon.domains.party.profiles.csv-pg.target.schema=master
mms.recon.domains.party.profiles.csv-pg.target.table=party
mms.recon.domains.party.profiles.csv-pg.target.fields[0]=party_name
mms.recon.domains.party.profiles.csv-pg.target.fields[1]=country_code
mms.recon.domains.party.profiles.csv-pg.target.fields[2]=status
