# party / mongo-pg
# MongoDB mongo.party -> PostgreSQL master.party
mms:
  recon:
    domains:
      party:
        profiles:
          mongo-pg:
            datasources:
              source: mongo
              target: landing
            migrationKey:
              type: SINGLE
              columns: [party_id]
            recon:
              mode: MISMATCH_DETAILS
            source:
              collection: party
              fields: [party_name, country_code, status]
              query: '{}'
            target:
              schema: master
              table: party
              fields: [party_name, country_code, status]
