# party / mongo-mongo
# MongoDB party_landing -> MongoDB party
mms.recon.domains.party.profiles.mongo-mongo.datasources.source=mongo
mms.recon.domains.party.profiles.mongo-mongo.datasources.target=mongo
mms.recon.domains.party.profiles.mongo-mongo.migrationKey.type=SINGLE
mms.recon.domains.party.profiles.mongo-mongo.migrationKey.columns[0]=party_id
mms.recon.domains.party.profiles.mongo-mongo.recon.mode=MISMATCH_DETAILS
mms.recon.domains.party.profiles.mongo-mongo.source.collection=party_landing
mms.recon.domains.party.profiles.mongo-mongo.source.fields[0]=party_name
mms.recon.domains.party.profiles.mongo-mongo.source.fields[1]=country_code
mms.recon.domains.party.profiles.mongo-mongo.source.fields[2]=status
mms.recon.domains.party.profiles.mongo-mongo.source.query={}
mms.recon.domains.party.profiles.mongo-mongo.target.collection=party
mms.recon.domains.party.profiles.mongo-mongo.target.fields[0]=party_name
mms.recon.domains.party.profiles.mongo-mongo.target.fields[1]=country_code
mms.recon.domains.party.profiles.mongo-mongo.target.fields[2]=status
mms.recon.domains.party.profiles.mongo-mongo.target.query={}
