# party / pg-pg-composite
# PostgreSQL landing.party -> PostgreSQL master.party (composite key)
mms.recon.domains.party.profiles.pg-pg-composite.datasources.source=landing
mms.recon.domains.party.profiles.pg-pg-composite.datasources.target=landing
mms.recon.domains.party.profiles.pg-pg-composite.migrationKey.type=COMPOSITE
mms.recon.domains.party.profiles.pg-pg-composite.migrationKey.columns[0]=party_id
mms.recon.domains.party.profiles.pg-pg-composite.migrationKey.columns[1]=country_code
mms.recon.domains.party.profiles.pg-pg-composite.migrationKey.separator=|
mms.recon.domains.party.profiles.pg-pg-composite.recon.mode=FIELD_DETAILS
mms.recon.domains.party.profiles.pg-pg-composite.recon.conditionFields[0]=party_name
mms.recon.domains.party.profiles.pg-pg-composite.recon.conditionFields[1]=status
mms.recon.domains.party.profiles.pg-pg-composite.source.schema=landing
mms.recon.domains.party.profiles.pg-pg-composite.source.table=party
mms.recon.domains.party.profiles.pg-pg-composite.source.fields[0]=party_name
mms.recon.domains.party.profiles.pg-pg-composite.source.fields[1]=status
mms.recon.domains.party.profiles.pg-pg-composite.target.schema=master
mms.recon.domains.party.profiles.pg-pg-composite.target.table=party
mms.recon.domains.party.profiles.pg-pg-composite.target.fields[0]=party_name
mms.recon.domains.party.profiles.pg-pg-composite.target.fields[1]=status
